build:
  image: python:2.7.12
  commands:
    - pip install -r requirements.txt
    - cp conf/gunicorn/gunicorn.cfg.py ./gunicorn.cfg.py
    - find . \( -name __pycache__ -o -name '*.pyc' \) -delete
    - tox
